/*
 * This file is the main driver for the Midnight bulletin board example.
 * The entry point is the run function, at the end of the file.
 * We expect the startup files (testnet-remote.ts, standalone.ts, etc.) to
 * call run with some specific configuration that sets the network addresses
 * of the servers this file relies on.
 */

import { createInterface, type Interface } from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import { WebSocket } from 'ws';
import { webcrypto } from 'crypto';
import {
  type VoteGuardianProviders,
  type PrivateStates,
  VoteGuardianAPI,
  utils,
  type VoteGuardianDerivedState,
  type DeployedVoteGuardianContract,
} from '@midnight-ntwrk/vote-guardian-api';
import { ledger, type Ledger, VOTE_STATE } from '@midnight-ntwrk/vote-guardian-contract';
import {
  type BalancedTransaction,
  createBalancedTx,
  type MidnightProvider,
  type UnbalancedTransaction,
  type WalletProvider,
} from '@midnight-ntwrk/midnight-js-types';
import { type Wallet } from '@midnight-ntwrk/wallet-api';
import * as Rx from 'rxjs';
import { type CoinInfo, nativeToken, Transaction, type TransactionId } from '@midnight-ntwrk/ledger';
import { Transaction as ZswapTransaction } from '@midnight-ntwrk/zswap';
import { NodeZkConfigProvider } from '@midnight-ntwrk/midnight-js-node-zk-config-provider';
import { type Resource, WalletBuilder } from '@midnight-ntwrk/wallet';
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { httpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { type Logger } from 'pino';
import { type Config, StandaloneConfig } from './config.js';
import type { StartedDockerComposeEnvironment, DockerComposeEnvironment } from 'testcontainers';
import { levelPrivateStateProvider } from '@midnight-ntwrk/midnight-js-level-private-state-provider';
import { type ContractAddress } from '@midnight-ntwrk/compact-runtime';
import { toHex } from '@midnight-ntwrk/midnight-js-utils';
import { getLedgerNetworkId, getZswapNetworkId } from '@midnight-ntwrk/midnight-js-network-id';
import axios from 'axios';

// @ts-expect-error: It's needed to make Scala.js and WASM code able to use cryptography
globalThis.crypto = webcrypto;

// @ts-expect-error: It's needed to enable WebSocket usage through apollo
globalThis.WebSocket = WebSocket;

/* **********************************************************************
 * getVoteGuardianLedgerState: a helper that queries the current state of
 * the data on the ledger, for a specific VoteGuardian contract.
 * Note that the Ledger type returned here is not some generic,
 * abstract ledger object, but specifically the type generated by
 * the Compact compiler to correspond to the ledger declaration
 * in the bulletin board contract.
 */

export const getVoteGuardianLedgerState = (
  providers: VoteGuardianProviders,
  contractAddress: ContractAddress,
): Promise<Ledger | null> =>
  providers.publicDataProvider
    .queryContractState(contractAddress)
    .then((contractState) => (contractState != null ? ledger(contractState.data) : null));

/* **********************************************************************
 * deployOrJoin: returns a contract, by prompting the user about
 * whether to deploy a new one or join an existing one and then
 * calling the appropriate helper.
 */

function uint8ArrayToString(uint8Array: Uint8Array): string {
  const decoder = new TextDecoder();
  return decoder.decode(uint8Array);
}

const DEPLOY_OR_JOIN_QUESTION = `
You can do one of the following:
  1. Deploy a new Vote Guardian contract
  2. Join an existing Vote Guardian contract
  3. Exit
Which would you like to do? `;

const deployOrJoin = async (
  providers: VoteGuardianProviders,
  rli: Interface,
  logger: Logger,
): Promise<VoteGuardianAPI | null> => {
  let api: VoteGuardianAPI | null = null;

  while (true) {
    const choice = await rli.question(DEPLOY_OR_JOIN_QUESTION);
    switch (choice) {
      case '1':
        api = await VoteGuardianAPI.deploy(providers, logger);
        if (api != null) {
          logger.info(`Deployed contract at address: ${api.deployedContractAddress}`);
        }
        return api;

      case '2':
        const secretKey = await rli.question('What is your secret key?');
        api = await VoteGuardianAPI.join(
          providers,
          await rli.question('What is the contract address (in hex)? '),
          secretKey,
          logger,
        );
        logger.info(`Joined contract at address: ${api.deployedContractAddress}`);
        return api;
      case '3':
        logger.info('Exiting...');
        return null;
      default:
        logger.error(`Invalid choice: ${choice}`);
    }
  }
};

/* **********************************************************************
 * displayLedgerState: shows the values of each of the fields declared
 * by the contract to be in the ledger state of the bulletin board.
 */

const displayQuestionsAndOptions = async (
  providers: VoteGuardianProviders,
  deployedVoteGuardianContract: DeployedVoteGuardianContract,
  logger: Logger,
): Promise<void> => {
  const contractAddress = deployedVoteGuardianContract.deployTxData.public.contractAddress;
  const ledgerState = await getVoteGuardianLedgerState(providers, contractAddress);
  if (ledgerState === null) {
    logger.info(`There is no Vote Guardian contract deployed at ${contractAddress}`);
  } else {
    logger.info('Printing voting question...');
    logger.info(`${ledgerState.voteQuestion} `);
    logger.info('Printing voting options...');
    for (const [key, value] of ledgerState.voteOptionMap) {
      logger.info(`Index: ${key}. Vote option: ${value.toString()}.`);
    }
  }
};

const displayLedgerState = async (
  providers: VoteGuardianProviders,
  deployedVoteGuardianContract: DeployedVoteGuardianContract,
  logger: Logger,
): Promise<void> => {
  const contractAddress = deployedVoteGuardianContract.deployTxData.public.contractAddress;
  const ledgerState = await getVoteGuardianLedgerState(providers, contractAddress);
  if (ledgerState === null) {
    logger.info(`There is no Vote Guardian contract deployed at ${contractAddress}`);
  } else {
    let votingState = '';
    if (ledgerState.voteState === VOTE_STATE.open) {
      votingState = 'open';
    } else if (ledgerState.voteState === VOTE_STATE.closed) {
      votingState = 'closed';
    }
    logger.info(`Current state is: '${votingState}'`);

    logger.info('Printing current voters and whether they have voted or not');
    // for (const [key, value] of ledgerState.votersMap) {
    //   logger.info(`Voter: ${toHex(key)}. Has voted: ${value.toString()}`);
    // }

    logger.info('Printing current votes list');
    for (const vote of ledgerState.votesList) {
      logger.info(`${vote} `);
    }

    logger.info(`Current total number of votes is ${ledgerState.voteCount}`);
    logger.info(`Voting question is: ${ledgerState.voteQuestion}`);
    logger.info('Printing voting options...');
    for (const [key, value] of ledgerState.voteOptionMap) {
      logger.info(`Index: ${key}. Vote option: ${value.toString()}.`);
    }
  }
};

/* **********************************************************************
 * displayPrivateState: shows the hex-formatted value of the secret key.
 */

const displayPrivateState = async (providers: VoteGuardianProviders, logger: Logger): Promise<void> => {
  const privateState = await providers.privateStateProvider.get('voteGuardianPrivateState');
  if (privateState === null) {
    logger.info(`There is no existing Vote Guardian private state`);
  } else {
    logger.info(`Current secret key is: ${toHex(privateState.secretKey)}`);
  }
};

/* **********************************************************************
 * displayDerivedState: shows the values of derived state which is made
 * by combining the ledger state with private state. In this example, the
 * derived state compares the poster key with the private secret key to
 * determine if the current user is the poster of the current message.
 */

// const displayDerivedState = (ledgerState: VoteGuardianDerivedState | undefined, logger: Logger) => {
//   if (ledgerState === undefined) {
//     logger.info(`No bulletin board state currently available`);
//   } else {
//     const boardState = ledgerState.state === STATE.occupied ? 'occupied' : 'vacant';
//     const latestMessage = ledgerState.state === STATE.occupied ? ledgerState.message : 'none';
//     logger.info(`Current state is: '${boardState}'`);
//     logger.info(`Current message is: '${latestMessage}'`);
//     logger.info(`Current instance is: ${ledgerState.instance}`);
//     logger.info(`Current poster is: '${ledgerState.isOwner ? 'you' : 'not you'}'`);
//   }
// };

/* **********************************************************************
 * mainLoop: the main interactive menu of the bulletin board CLI.
 * Before starting the loop, the user is prompted to deploy a new
 * contract or join an existing one.
 */

const MAIN_LOOP_QUESTION = `
You can do one of the following:
  9. Verify Identity
  0. Create a voting
  1. Cast a vote
  2. Add a voter
  3. Close the voting
  4. Count the votes
  5. Display the current ledger state (known by everyone)
  6. Display the current private state (known only to this DApp instance)
  7. Exit
  8. Add options
Which would you like to do? `;

const mainLoop = async (providers: VoteGuardianProviders, rli: Interface, logger: Logger): Promise<void> => {
  const VoteGuardianApi = await deployOrJoin(providers, rli, logger);
  if (VoteGuardianApi === null) {
    return;
  }

  /* TODO: Εδώ θα μπει η εκτ΄ύπωση της ερώτησης και των διαθέσιμων ερωτήσεων*/
  await displayQuestionsAndOptions(providers, VoteGuardianApi.deployedContract, logger);

  let currentState: VoteGuardianDerivedState | undefined;
  const stateObserver = {
    next: (state: VoteGuardianDerivedState) => (currentState = state),
  };
  const subscription = VoteGuardianApi.state$.subscribe(stateObserver);
  // if (VoteGuardianApi != null) {
  //   await VoteGuardianApi.add_voter();
  // }
  try {
    let options_count = 1;
    while (true) {
      await displayQuestionsAndOptions(providers, VoteGuardianApi.deployedContract, logger);
      const choice = await rli.question(MAIN_LOOP_QUESTION);
      switch (choice) {
        case '9': {
          const username = await rli.question('Enter username: ');
          const password = await rli.question('Enter password: ');
          try {
            const response = await axios.post('http://localhost:3000/login', {
              username,
              password,
            });

            const signature = response.data.signature;
            const credential = response.data.credential;
            console.log('Signature:', signature);

            return signature; // You can use this variable later
          } catch (error) {
            console.error('Error:', error);
          }
        }

        case '0': {
          const question = await rli.question(`What is the question? `);
          await VoteGuardianApi.create_voting(question);
          break;
        }

        case '1': {
          const vote = await rli.question(`What vote do you wana cast? `);
          await VoteGuardianApi.cast_vote(vote);
          break;
        }
        case '2':
          const voter_public_key_str = await rli.question(`What is the public key you want to add? `);
          // const voter_secret_key = await rli.question(`What is the secret key of the voter you want to add ?`);
          // let coter_secret_key_u8arr = new TextEncoder().encode(voter_secret_key);
          // await VoteGuardianApi.add_voter(coter_secret_key_u8arr);
          const voter_public_key_u8 = utils.hexToBytes(voter_public_key_str);

          await VoteGuardianApi.add_voter(voter_public_key_u8);
          console.log('inside add voter');
          break;
        case '3':
          await VoteGuardianApi.close_voting();

        case '4':
          console.log('count_votes');

        case '5':
          await displayLedgerState(providers, VoteGuardianApi.deployedContract, logger);
          break;
        case '6':
          await displayPrivateState(providers, logger);
          break;
        case '7':
          logger.info('Exiting...');
          return;
        case '8':
          const vote_option = await rli.question(`What is the option?`);
          await VoteGuardianApi.add_option(vote_option, options_count.toString());
          options_count += 1;
        default:
          logger.error(`Invalid choice: ${choice}`);
      }
    }
  } finally {
    // While we allow errors to bubble up to the 'run' function, we will always need to dispose of the state
    // subscription when we exit.
    subscription.unsubscribe();
  }
};

/* **********************************************************************
 * createWalletAndMidnightProvider: returns an object that
 * satifies both the WalletProvider and MidnightProvider
 * interfaces, both implemented in terms of the given wallet.
 */

const createWalletAndMidnightProvider = async (wallet: Wallet): Promise<WalletProvider & MidnightProvider> => {
  const state = await Rx.firstValueFrom(wallet.state());
  return {
    coinPublicKey: state.coinPublicKey,
    balanceTx(tx: UnbalancedTransaction, newCoins: CoinInfo[]): Promise<BalancedTransaction> {
      return wallet
        .balanceTransaction(
          ZswapTransaction.deserialize(tx.serialize(getLedgerNetworkId()), getZswapNetworkId()),
          newCoins,
        )
        .then((tx) => wallet.proveTransaction(tx))
        .then((zswapTx) => Transaction.deserialize(zswapTx.serialize(getZswapNetworkId()), getLedgerNetworkId()))
        .then(createBalancedTx);
    },
    submitTx(tx: BalancedTransaction): Promise<TransactionId> {
      return wallet.submitTransaction(tx);
    },
  };
};

/* **********************************************************************
 * waitForFunds: wait for tokens to appear in a wallet.
 *
 * This is an interesting example of watching the stream of states
 * coming from the pub-sub indexer.  It watches both
 *  1. how close the state is to present reality and
 *  2. the balance held by the wallet.
 */

const waitForFunds = (wallet: Wallet, logger: Logger) =>
  Rx.firstValueFrom(
    wallet.state().pipe(
      Rx.throttleTime(10_000),
      Rx.tap((state) => {
        const scanned = state.syncProgress?.synced ?? 0n;
        const total = state.syncProgress?.total.toString() ?? 'unknown number';
        logger.info(`Wallet scanned ${scanned} blocks out of ${total}`);
      }),
      Rx.filter((state) => {
        // Let's allow progress only if wallet is close enough
        const synced = state.syncProgress?.synced ?? 0n;
        const total = state.syncProgress?.total ?? 1_000n;
        return total - synced < 100n;
      }),
      Rx.map((s) => s.balances[nativeToken()] ?? 0n),
      Rx.filter((balance) => balance > 0n),
    ),
  );

/* **********************************************************************
 * buildWalletAndWaitForFunds: the main function that creates a wallet
 * and waits for tokens to appear in it.  The various "buildWallet"
 * functions all arrive here after collecting information for the
 * arguments.
 */

const buildWalletAndWaitForFunds = async (
  { indexer, indexerWS, node, proofServer }: Config,
  logger: Logger,
  seed: string,
): Promise<Wallet & Resource> => {
  const wallet = await WalletBuilder.buildFromSeed(
    indexer,
    indexerWS,
    proofServer,
    node,
    seed,
    getZswapNetworkId(),
    'warn',
  );
  wallet.start();
  const state = await Rx.firstValueFrom(wallet.state());
  logger.info(`Your wallet seed is: ${seed}`);
  logger.info(`Your wallet address is: ${state.address}`);
  let balance = state.balances[nativeToken()];
  if (balance === undefined || balance === 0n) {
    logger.info(`Your wallet balance is: 0`);
    logger.info(`Waiting to receive tokens...`);
    balance = await waitForFunds(wallet, logger);
  }
  logger.info(`Your wallet balance is: ${balance}`);
  return wallet;
};

// Generate a random see and create the wallet with that.
const buildFreshWallet = async (config: Config, logger: Logger): Promise<Wallet & Resource> =>
  await buildWalletAndWaitForFunds(config, logger, toHex(utils.randomBytes(32)));

// Prompt for a seed and create the wallet with that.
const buildWalletFromSeed = async (config: Config, rli: Interface, logger: Logger): Promise<Wallet & Resource> => {
  const seed = await rli.question('Enter your wallet seed: ');
  return await buildWalletAndWaitForFunds(config, logger, seed);
};

/* ***********************************************************************
 * This seed gives access to tokens minted in the genesis block of a local development node - only
 * used in standalone networks to build a wallet with initial funds.
 */
const GENESIS_MINT_WALLET_SEED = '0000000000000000000000000000000000000000000000000000000000000042';

/* **********************************************************************
 * buildWallet: unless running in a standalone (offline) mode,
 * prompt the user to tell us whether to create a new wallet
 * or recreate one from a prior seed.
 */

const WALLET_LOOP_QUESTION = `
You can do one of the following:
  1. Build a fresh wallet
  2. Build wallet from a seed
  3. Exit
Which would you like to do? `;

const buildWallet = async (config: Config, rli: Interface, logger: Logger): Promise<(Wallet & Resource) | null> => {
  if (config instanceof StandaloneConfig) {
    return await buildWalletAndWaitForFunds(config, logger, GENESIS_MINT_WALLET_SEED);
  }
  while (true) {
    const choice = await rli.question(WALLET_LOOP_QUESTION);
    switch (choice) {
      case '1':
        return await buildFreshWallet(config, logger);
      case '2':
        return await buildWalletFromSeed(config, rli, logger);
      case '3':
        logger.info('Exiting...');
        return null;
      default:
        logger.error(`Invalid choice: ${choice}`);
    }
  }
};

const mapContainerPort = (env: StartedDockerComposeEnvironment, url: string, containerName: string) => {
  const mappedUrl = new URL(url);
  const container = env.getContainer(containerName);

  mappedUrl.port = String(container.getFirstMappedPort());

  return mappedUrl.toString().replace(/\/+$/, '');
};

/* **********************************************************************
 * run: the main entry point that starts the whole bulletin board CLI.
 *
 * If called with a Docker environment argument, the application
 * will wait for Docker to be ready before doing anything else.
 */

export const run = async (config: Config, logger: Logger, dockerEnv?: DockerComposeEnvironment): Promise<void> => {
  const rli = createInterface({ input, output, terminal: true });
  let env;
  if (dockerEnv !== undefined) {
    env = await dockerEnv.up();

    if (config instanceof StandaloneConfig) {
      config.indexer = mapContainerPort(env, config.indexer, 'voteguardian-indexer');
      config.indexerWS = mapContainerPort(env, config.indexerWS, 'voteguardian-indexer');
      config.node = mapContainerPort(env, config.node, 'voteguardian-node');
      config.proofServer = mapContainerPort(env, config.proofServer, 'voteguardian-proof-server');
    }
  }
  const wallet = await buildWallet(config, rli, logger);

  // if (wallet != null) {
  //   async function sendNativeToken(address: string, amount: bigint): Promise<string> {
  //     const transferRecipe = await wallet!.transferTransaction([
  //       {
  //         amount,
  //         receiverAddress: address,
  //         type: nativeToken(),
  //       },
  //     ]);
  //     const transaction = await wallet!.proveTransaction(transferRecipe);
  //     return await wallet!.submitTransaction(transaction);
  //   }

  //   await sendNativeToken(
  //     '8d1e857e16eec730b784a343654671c6d9ebe14c48a81570880a0c880365b1bd|030087e855e8c04bd42f518267b1f729a72b7b56f57d0a5b8134517630bdfce1955eee49854c41e984cac6010254b865a22d50ffeb31248f291b',
  //     10000000000n,
  //   );
  // }

  try {
    if (wallet !== null) {
      const walletAndMidnightProvider = await createWalletAndMidnightProvider(wallet);
      // εδώ φτιάχνονται οι providers και μετά δίνονται όπου χρειάζονται providers
      const providers = {
        privateStateProvider: levelPrivateStateProvider<PrivateStates>({
          privateStateStoreName: config.privateStateStoreName,
        }),
        // μέσω του publicDataProvider μπορώ να βλέπω το public state του contract
        publicDataProvider: indexerPublicDataProvider(config.indexer, config.indexerWS),

        // provider για τα zk proofs. Δίνει το path όπου βρίσκονται τα keys και τα circuits
        zkConfigProvider: new NodeZkConfigProvider<
          'cast_vote' | 'close_voting' | 'add_voter' | 'create_voting' | 'add_option'
        >(config.zkConfigPath),
        proofProvider: httpClientProofProvider(config.proofServer),
        walletProvider: walletAndMidnightProvider,
        midnightProvider: walletAndMidnightProvider,
      };
      await mainLoop(providers, rli, logger);
    }
  } catch (e) {
    if (e instanceof Error) {
      logger.error(`Found error '${e.message}'`);
      logger.info('Exiting...');
      1;
      logger.debug(`${e.stack}`);
    } else {
      throw e;
    }
  } finally {
    try {
      rli.close();
      rli.removeAllListeners();
    } catch (e) {
    } finally {
      try {
        if (wallet !== null) {
          await wallet.close();
        }
      } catch (e) {
      } finally {
        try {
          if (env !== undefined) {
            await env.down();
            logger.info('Goodbye');
            process.exit(0);
          }
        } catch (e) {}
      }
    }
  }
};
