/**
 * Provides utility functions.
 *
 * @module
 */
// const crypto = require('crypto');
/**
 * Generates a buffer containing a series of randomly generated bytes.
 *
 * @param length The number of bytes to generate.
 * @returns A `Uint8Array` representing `length` randomly generated bytes.
 */
export const randomBytes = (length: number): Uint8Array => {
  const bytes = new Uint8Array(length);
  crypto.getRandomValues(bytes);
  return bytes;
};

export const hexToBytesNull = (hex: string) => {
  if (hex === null) {
    return null;
  }

  if (hex.length % 2 !== 0) {
    throw new Error('Invalid hex string');
  }

  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < hex.length; i += 2) {
    bytes[i / 2] = parseInt(hex.slice(i, i + 2), 16);
  }
  return bytes;
};

export const hexToBytes = (hex: string) => {
  if (hex.length % 2 !== 0) {
    throw new Error('Invalid hex string');
  }

  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < hex.length; i += 2) {
    bytes[i / 2] = parseInt(hex.slice(i, i + 2), 32);
  }
  return bytes;
};

export function stringToUint8Array(input: string): Uint8Array {
  const encoder = new TextEncoder();
  return encoder.encode(input);
}

// export function hash_secret_key(secretKey: string): Uint8Array {
//   const hashSHA256 = (data: string) => {
//     return crypto.createHash('sha256').update(data, 'hex').digest('hex');
//   };
//   const publicKeyHex = hashSHA256(secretKey);
//   return hexToBytes(publicKeyHex);
// }
